### ISSUE TITLE
TODO 3, every collaborators: Clone Master Repo + pull request

### ISSUE THREAD

**Issue by MattYu** [JoComp27/SOEN341-SA1#5]
- [x] Ming made pull request
- [x] Refat made pull request
- [x] Jonathan made pull request
- [x] Jessica made pull request
- [x] Eric made pull request
- [x] Kersten made pull request
- [x] Sumit made pull request
- [x] Aida made pull request

**Comment by marois** [comment]
@JoComp27 Hi Jo, Can you change the scigilian.com email address associated with JoComp27, since these emails are being forwarded to me, thanks.

Good luck on your project!
